### numpy中random模块

In [1]:
import numpy as np

In [2]:
# 总结：
# 需要生成浮点数，建议用np.random.uniform，可以改变数值上下限；
# 需要生成0-1之间的浮点数，则np.random.random_sample, np.random.rand也可以；
# 需要生成整数，建议用np.random.randint;

#### 1. np.random.uniform

In [3]:
# 生成满足uniform分布的随机数，数值在[low, high)之间, size指定生成随机数的个数
# low默认是0，也可以是数组类型的
# high默认是1.0， 也可以是数组类型的
# size默认是None，只返回一个值, size也可以是个数组形式(a, b)
np.random.uniform(low=1.0, high=20, size=10)

array([14.96546189,  3.25930734, 17.72916611, 13.79613835,  1.31905297,
        9.65873958, 11.18820885,  6.93133544,  6.12709601, 10.6089131 ])

In [4]:
np.random.uniform(low=1.0, high=2.0, size=(3, 5))

array([[1.64949947, 1.74139625, 1.84836051, 1.75594918, 1.18349726],
       [1.03090178, 1.10214319, 1.22910201, 1.02468345, 1.5961814 ],
       [1.8396259 , 1.73150742, 1.51092092, 1.1252429 , 1.16737134]])

In [5]:
np.random.uniform(low=[3, 5, 7], high=[10, 12, 19]) 
# 分别生成3~10， 5~12， 7~19的三个数

array([ 9.69780092, 11.15270531,  8.76833455])

#### 2.np.random.random_sample

In [6]:
# 生成随机数，数值在[0.0, 1.0)之间，随机数数量由size指定
np.random.random_sample(size=5)

array([0.08630491, 0.84456741, 0.61651015, 0.08923031, 0.30835068])

In [7]:
np.random.random_sample(size=(2, 4))

array([[0.70742855, 0.27856844, 0.91542636, 0.25877437],
       [0.63588257, 0.87425613, 0.00740846, 0.16047293]])

#### 3. np.random.rand

In [8]:
# 生成随机数，数值在[0.0, 1.0）之间的数值，随机数数量由参数指定
np.random.rand(3, 4, 2)

array([[[0.43442966, 0.47205527],
        [0.19392614, 0.47464647],
        [0.85697724, 0.70667345],
        [0.48698029, 0.99368623]],

       [[0.06680528, 0.75166595],
        [0.68903373, 0.11599593],
        [0.22126782, 0.25593217],
        [0.82069643, 0.94929714]],

       [[0.19440486, 0.5038324 ],
        [0.77469756, 0.63511322],
        [0.02943535, 0.35579167],
        [0.37883421, 0.61300952]]])

#### 4. np.random.randint

In [9]:
# 生成整形随机数，数值大小在[low, high)之间，随机数数量由size指定

In [10]:
np.random.randint(low=10, high=20, size=(2, 4))

array([[16, 17, 11, 19],
       [15, 15, 11, 11]])